module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: {
    standard: [
      /^home-/,
      /^research-motion-/,
      /^theme-/,
      /^is-/,
      /^fa-/,
      /^fa[srbl]?$/,
      /^ai-/,
      /^ninja-/,
      /^cinematic-/,
      /^case-/,
      "post-header-field",
      "has-spotlight",
      "collapse",
      "collapsing",
      "show",
      "dropdown-menu",
      "dropdown-item",
      "table",
      "table-dark",
      "table-hover",
      "table-responsive",
      "af-tooltip",
      "af-popover",
      "font-weight-bold",
      "font-weight-medium",
      "font-weight-lighter",
      "medium-zoom-overlay",
      "medium-zoom-image--opened",
    ],
    deep: [/^home-/, /^theme-/, /^research-motion-/, /^ninja-/],
    greedy: [
      /data-theme/,
      /data-theme-mode/,
      /home-motion/,
      /home-research-motion/,
      /home-story-rail/,
      /home-visible/,
      /research-motion/,
      /theme-menu/,
      /theme-toggle/,
      /is-active/,
      /view-transition/,
    ],
    keyframes: [/^home-/, /^site-/, /^cinematic-/],
    variables: [
      /^--global-/,
      /^--home-/,
      /^--md-lite-/,
      /^--motion-/,
      /^--research-motion-/,
      /^--measure-/,
      /^--type-/,
      /^--spot-/,
      /^--tilt-/,
      /^--case-/,
    ],
  },
};
